name: WhatsApp Bot

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libgbm-dev
        npm install
    
    - name: Run Bot
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        export DISPLAY=:99
        npm start
    
    - name: Keep Alive
      run: |
        echo "Monitoring bot status..."
        while sleep 60; do
          echo "[$(date +'%H:%M:%S')] Workflow active"
        done
