name: WhatsApp TagBot CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run WhatsApp Bot
      run: xvfb-run --auto-servernum npm start
      env:
        DISPLAY: ":99"
    
    - name: Keep alive (prevent timeout)
      run: sleep 300
